### ISSUE TITLE
ServerDisconnect Error

### ISSUE THREAD

**Issue by BenediktMKuehne** [cve-search/CveXplore#205]
I need some help with the following output:
> Traceback (most recent call last):
>   File "/home/benedikt/embark/emba/external/emba_venv/bin/cvexplore", line 8, in <module>
>     sys.exit(main())
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/core.py", line 1666, in invoke
>     rv = super().invoke(ctx)
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/CveXplore/cli_cmds/db_cmds/commands.py", line 28, in initialize_cmd
>     ctx.obj["data_source"].database.initialize()
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/CveXplore/database/maintenance/main_updater.py", line 167, in initialize
>     cve_pop.populate()
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/CveXplore/database/maintenance/Sources_process.py", line 904, in populate
>     self.process_downloads()
>   File "/home/benedikt/embark/emba/external/emba_venv/lib/python3.10/site-packages/CveXplore/database/maintenance/Sources_process.py", line 796, in process_downloads
>     for item in data_list["vulnerabilities"]
> TypeError: 'ServerDisconnectedError' object is not subscriptable

Version is:
`CveXplore==0.3.17`

Within the logs I see some "...forbidden..." message
[cvexplore-init.log](https://github.com/cve-search/CveXplore/files/13424293/cvexplore-init.log)

Any Idea what could cause this?

**Comment by P-T-I** [comment]
yeah; that's the NIST API giving back a 403; I've normally seen those coming back when to many requests are send towards the NIST API. You would expect a 429 coming back, but they have chosen to go for a 403. CveXplore retries 5 times with an exponential back-off; after that it simply gives up and fails with an error message. You should see those retries in your debug logging...

**Comment by BenediktMKuehne** [comment]
Would it be possible to add a small output like
`CveXplore.database.maintenance.main_updater - ERROR   - Foo Bar` or an error code when that happens

**Comment by P-T-I** [comment]
Pretty sure this can be done; let me check!

**Comment by P-T-I** [comment]
@BenediktMKuehne done in 4ac13dc

**Comment by BenediktMKuehne** [comment]
Thank you 🥳
