### ISSUE TITLE
Add additional field to the CVE

### ISSUE THREAD

**Issue by lbtuda** [cve-search/CveXplore#238]
Hi, is there a reason the  `cve["configurations"]` field is not stored? We would like to do some additional queries on this filed, as NIST is missing some CPEs and we want to work around that by doing a lookup on the cpe stem and then filter with some additional logic if the cpe with its version would match the candidates we got by searching for the stem.

**Comment by P-T-I** [comment]
I see no issue in storing that additional field; are you filing a PR or shall I look into it?

**Comment by P-T-I** [comment]
Are you looking for the entire field to store? Or just the matchCriteriaId?

**Comment by P-T-I** [comment]
Bare in mind that CveXplore is already performing some logic for getting the right vulnerable configurations into the database. Are you planning on performing some similar queries? Is the lookup you are talking about a lookup via the NIST API or a local database lookup?

**Comment by P-T-I** [comment]
Ok; would that logic be something you're willing to incorporate into CveXplore?

**Comment by P-T-I** [comment]
Ok; but your algo does yield additional matches; or not? If so; what are the differences?
