### ISSUE TITLE
Database Updates fail when filtering out Deprecated CPEs

### ISSUE THREAD

**Issue by SebastianS0** [cve-search/CveXplore#258]
Bug in `sources_process.py` [Link to Code](https://github.com/cve-search/CveXplore/blob/80ebd624f68d7505133811cb270895bcc7e15a25/CveXplore/core/database_maintenance/sources_process.py#L235C31-L244C106)

In this code `processed_items`  contains objects of type `None` for the cpes that are deprecated.
This causes `self._db_bulk_writer(processed_items)` to fail, as it doesn't expect objects of Type `None` See [PyMongo Docs](https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.bulk_write).

A temporary fix would be to just filter out objects of type None with:
`processed_items = [item for item in processed_items if item is not None]` **but this will leave deprecated cpes in the database.**
or enabling deprecated cpes.

CPEs that caused this issue today:
[Deprecated_CPEs.json](https://github.com/cve-search/CveXplore/files/13960984/Deprecated_CPEs.json)

Version used: `cve-search: 5.0.0` `cveXplore: 0.3.20`

**Comment by P-T-I** [comment]
@SebastianS0 Thanks for reporting; but I believe this is already fixed in current master branch of this repo; could you check?

**Comment by SebastianS0** [comment]
Yes it doesn't seem to be happening on the latest commit. Could you maybe create a release for this Issue? 
Also wouldn't it be a better fix to actually delete the old deprecated CPE instead of just ignoring it by returning None? 
Since now you'll have have CPEs in the database that are actually deprecated, but have a deprecated field with the value False.

**Comment by P-T-I** [comment]
I'm planning to create a new release soon; would like to wait to have other fixes incorporated as well. 

If you update the database the deprecated cpe's are still there; if you populate from scratch they should not be there at all...

**Comment by P-T-I** [comment]
@SebastianS0 https://github.com/cve-search/CveXplore/releases/tag/v0.3.21; new release, will start on adjusting cve-search tomorrow
