### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type' 

### ISSUE THREAD

**Issue by kinimoas** [cve-search/CveXplore#261]
Hi all,

I see the following error - probably a dependency issue:

cvexplore database initialize 
Traceback (most recent call last):
  File "/usr/local/bin/cvexplore", line 5, in <module>
    from CveXplore.cli import main
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/__init__.py", line 1, in <module>
    from CveXplore.main import CveXplore
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/main.py", line 14, in <module>
    from CveXplore.api.connection.api_db import ApiDatabaseSource
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/api/connection/api_db.py", line 5, in <module>
    from CveXplore.api.helpers.cve_search_api import CveSearchApi
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/api/helpers/cve_search_api.py", line 7, in <module>
    from CveXplore.api.api_base_class import ApiBaseClass
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/api/api_base_class.py", line 11, in <module>
    class ApiBaseClass(object):
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/api/api_base_class.py", line 64, in ApiBaseClass
    data: dict | str = None,
TypeError: unsupported operand type(s) for |: 'type' and 'type'

I've installed cveXplore with pip3 on a debian bullseye system:

sudo pip3 install  cvexplore
Collecting cvexplore
  Downloading CveXplore-0.3.19-py3-none-any.whl (92 kB)
     |████████████████████████████████| 92 kB 75 kB/s 
Collecting aiohttp~=3.8.6
  Downloading aiohttp-3.8.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 8.2 MB/s 
Collecting python-dotenv~=1.0.0
  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Collecting python-dateutil==2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 50.4 MB/s 
Collecting ijson~=3.2.3
  Downloading ijson-3.2.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (111 kB)
     |████████████████████████████████| 111 kB 99.1 MB/s 
Requirement already satisfied: ansicolors==1.1.8 in /usr/lib/python3/dist-packages (from cvexplore) (1.1.8)
Collecting requests==2.31.0
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 207 kB/s 
Collecting pandas~=2.1.2
  Downloading pandas-2.1.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.3 MB)
     |████████████████████████████████| 12.3 MB 90.0 MB/s 
Collecting click-completion==0.5.2
  Downloading click-completion-0.5.2.tar.gz (10 kB)
Collecting pymongo~=4.5.0
  Downloading pymongo-4.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (670 kB)
     |████████████████████████████████| 670 kB 73.0 MB/s 
Collecting tqdm==4.66.1
  Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 1.2 MB/s 
Collecting aioretry~=5.0.2
  Downloading aioretry-5.0.2-py3-none-any.whl (5.8 kB)
Collecting urllib3~=2.0.6
  Downloading urllib3-2.0.7-py3-none-any.whl (124 kB)
     |████████████████████████████████| 124 kB 48.1 MB/s 
Collecting dicttoxml==1.7.16
  Downloading dicttoxml-1.7.16-py3-none-any.whl (24 kB)
Collecting click==8.1.7
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 1.7 MB/s 
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from click-completion==0.5.2->cvexplore) (2.11.3)
Requirement already satisfied: shellingham in /usr/lib/python3/dist-packages (from click-completion==0.5.2->cvexplore) (1.3.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from click-completion==0.5.2->cvexplore) (1.16.0)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
     |████████████████████████████████| 142 kB 90.1 MB/s 
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.31.0->cvexplore) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.31.0->cvexplore) (2020.6.20)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (240 kB)
     |████████████████████████████████| 240 kB 80.6 MB/s 
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp~=3.8.6->cvexplore) (20.3.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/lib/python3/dist-packages (from aiohttp~=3.8.6->cvexplore) (1.6.3)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/lib/python3/dist-packages (from aiohttp~=3.8.6->cvexplore) (5.1.0)
Collecting numpy<2,>=1.22.4
  Downloading numpy-1.26.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     |████████████████████████████████| 18.2 MB 76.0 MB/s 
Collecting tzdata>=2022.1
  Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
     |████████████████████████████████| 346 kB 54.1 MB/s 
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas~=2.1.2->cvexplore) (2021.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/lib/python3/dist-packages (from pymongo~=4.5.0->cvexplore) (2.0.0)
Building wheels for collected packages: click-completion
  Building wheel for click-completion (setup.py) ... done
  Created wheel for click-completion: filename=click_completion-0.5.2-py3-none-any.whl size=11193 sha256=74099d945b92a9cd7bee06aa55bd54b472868b8dcfc648c2114b5625703401c5
  Stored in directory: /root/.cache/pip/wheels/f1/23/55/8287077a0e274c8d7ddf94fb623cb481cd0f4512d1a5062603
Successfully built click-completion
Installing collected packages: frozenlist, urllib3, tzdata, python-dateutil, numpy, click, charset-normalizer, async-timeout, aiosignal, tqdm, requests, python-dotenv, pymongo, pandas, ijson, dicttoxml, click-completion, aioretry, aiohttp, cvexplore
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.26.5
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'urllib3'. No files were found to uninstall.
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.1
    Not uninstalling python-dateutil at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'python-dateutil'. No files were found to uninstall.
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Not uninstalling numpy at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'numpy'. No files were found to uninstall.
  Attempting uninstall: click
    Found existing installation: click 7.1.2
    Not uninstalling click at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'click'. No files were found to uninstall.
  Attempting uninstall: async-timeout
    Found existing installation: async-timeout 3.0.1
    Not uninstalling async-timeout at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'async-timeout'. No files were found to uninstall.
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.65.0
    Uninstalling tqdm-4.65.0:
      Successfully uninstalled tqdm-4.65.0
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Not uninstalling requests at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'requests'. No files were found to uninstall.
  Attempting uninstall: python-dotenv
    Found existing installation: python-dotenv 0.15.0
    Not uninstalling python-dotenv at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'python-dotenv'. No files were found to uninstall.
  Attempting uninstall: pymongo
    Found existing installation: pymongo 3.11.0
    Not uninstalling pymongo at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pymongo'. No files were found to uninstall.
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Not uninstalling pandas at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pandas'. No files were found to uninstall.
  Attempting uninstall: ijson
    Found existing installation: ijson 3.1.4
    Not uninstalling ijson at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'ijson'. No files were found to uninstall.
  Attempting uninstall: dicttoxml
    Found existing installation: dicttoxml 1.7.4
    Not uninstalling dicttoxml at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'dicttoxml'. No files were found to uninstall.
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.7.4
    Not uninstalling aiohttp at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'aiohttp'. No files were found to uninstall.
Successfully installed aiohttp-3.8.6 aioretry-5.0.2 aiosignal-1.3.1 async-timeout-4.0.3 charset-normalizer-3.3.2 click-8.1.7 click-completion-0.5.2 cvexplore-0.3.19 dicttoxml-1.7.16 frozenlist-1.4.1 ijson-3.2.3 numpy-1.26.3 pandas-2.1.4 pymongo-4.5.0 python-dateutil-2.8.2 python-dotenv-1.0.1 requests-2.31.0 tqdm-4.66.1 tzdata-2023.4 urllib3-2.0.7

Where possible, I tried to use python3 libraries from the distribution, only installing unavailable ones from pip3

Can you please give guidance on what needs to be updated?

Thanks.

**Comment by P-T-I** [comment]
You are on python 3.9; CveXplore uses typing; which I believe is only supported from python 3.10 and up. So you will need to update your python version.

**Comment by kinimoas** [comment]
Thanks for the feedback. Unfortunately, I'm not familiar with the typing system of python. 

However, the docs https://docs.python.org/3/library/typing.html suggest, that typing was introduced with Version 3.5. 

Apparently, the typing_extensions allows backport of new features of the typing system. This is installed:

```
sudo pip3 install typing_extensions
Requirement already satisfied: typing_extensions in /usr/lib/python3/dist-packages (3.7.4.3)
```

Based on the description in https://typing-extensions.readthedocs.io/en/latest/# 

I changed the import in /usr/local/lib/python3.9/dist-packages/CveXplore/api/api_base_class.py

from
`from typing import Any`
to
`from typing_extensions import Any`

But this seems not to work

```
cve@cveTool:~$ cvexplore database initialize
Traceback (most recent call last):
  File "/usr/local/bin/cvexplore", line 5, in <module>
    from CveXplore.cli import main
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/__init__.py", line 1, in <module>
    from CveXplore.main import CveXplore
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/main.py", line 14, in <module>
    from CveXplore.api.connection.api_db import ApiDatabaseSource
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/api/connection/api_db.py", line 5, in <module>
    from CveXplore.api.helpers.cve_search_api import CveSearchApi
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/api/helpers/cve_search_api.py", line 7, in <module>
    from CveXplore.api.api_base_class import ApiBaseClass
  File "/usr/local/lib/python3.9/dist-packages/CveXplore/api/api_base_class.py", line 4, in <module>
    from typing_extensions import Any
ImportError: cannot import name 'Any' from 'typing_extensions' (/usr/lib/python3/dist-packages/typing_extensions.py)

```

I would prefer not to install python 3.10 if this can be achieved with typing_extensions

Any thoughts are welcome

**Comment by kinimoas** [comment]
I will migrate to python 3.10 or later.

Would you please consider to set appropriate dependecies -  CveXplore seems not to be compatible with python < 3.10 and should thus not be installed from pip.

Kind regards
