### ISSUE TITLE
Fix for #268

### ISSUE THREAD

**Issue by maxime-huyghe** [cve-search/CveXplore#273]
Hello again,
I accidentally introduced a crash in #268. That was due to insufficient testing on my part, and I'd like to apologize for that.
`CVEDownloads.add_full_cve_info_from_cpeuri` should have been an instance method and should have `self.stem()` instead of `CVEDownloads.stem()`
I will attach a PR as soon as I finish testing my fix properly.

**Comment by P-T-I** [comment]
@maxime-huyghe Hi; no problem, looking forward to it! I, however, cannot locate the issue you are referring to... Are you sure it made it to master branch?

**Comment by oh2fih** [comment]
From `commit 84f678c44a4426f7da557b2b15fe5b67fa39457e (HEAD -> master, origin/master, origin/HEAD)` I couldn't find anything with `grep "CVEDownloads.stem(" -rs .`, either. In `source_process.py` that contains the class `CVEDownloads()`, everything is referring correctly to the `self.stem()`:

```
$ grep ".stem(" ./CveXplore/core/database_maintenance/sources_process.py
            "stem": self.stem(item["cpeName"]),
                    "stem": self.stem(cpeuri["criteria"]),
                    "stem": self.stem(cpeuri["criteria"]),
                    "stem": self.stem(cpeuri["criteria"]),
                    "stem": self.stem(cpeuri["criteria"]),
                    "stem": self.stem(cpeuri["criteria"]),
                    "stem": self.stem(cpeuri["criteria"]),
                "stem": self.stem(cpeuri["criteria"]),
                "stem": self.stem(cpeuri["criteria"]),
                                        self.stem(cpeuri["criteria"]),
                                        self.stem(cpeuri["criteria"]),
                                    self.stem(cpeuri["criteria"]),
```

You might indeed be on a dev branch that still has this mistake.

**Comment by maxime-huyghe** [comment]
Seems like the issue was limited to my private fork, thanks for checking
