### ISSUE TITLE
Partial repopulation in case NVD API fails

### ISSUE THREAD

**Issue by oh2fih** [cve-search/CveXplore#299]
There have been problems with the NVD API for a few days: it has been either slow or returning 503 without completely failing. As a result, same updates are only partly successful. Currently, the only option would be repopulating the entire database, but due to the same problems that would result in more CVEs missing.

Currently, `source_process.py:158-161` compares the `lastModified` date of the most recent CPE, and `703-706` does the same for CVEs:

```
            else:
                last_mod_start_date = self.database[self.feed_type.lower()].find_one(
                    {}, {"lastModified": 1}, sort=[("lastModified", -1)]
                )
```

We need a solution to define a timestamp that could be used instead, causing all items after that timestamp to be fetched and updated regardless if they are already there, inserting the missing documents.

**Comment by oh2fih** [comment]
> That's a very good point, that would be great! The NIST API gives a lot of causes of concern.... I've opened #221 in the past; if NIST's API keeps erroring out, this might be a feasible alternative; don't you think?

Using the files might work for now, but we moved to the API mainly for the reason that the JSON feeds had been planned to retire in 2023, although it has other advantages, too. The retirement is currently postponed to "in 2024" in the [timeline](https://nvd.nist.gov/General/News/change-timeline).

> | Timeline | |
> | :--- | :--- |
> | December 2023 | The NVD will retire all 1.0 APIs on December 18th. | 
> | 2024 | The NVD will retire the Legacy Data Feed Files once improvements for bulk download capabilities of the NVD dataset are implemented. |

While we could guess it might be postponed again, I'm not that sure we should be building new features over deprecated data sources.

The [latest status update](https://www.nist.gov/itl/nvd) says:

> **May 29, 2024**: NIST has awarded a contract for additional processing support for incoming Common Vulnerabilities and Exposures (CVEs) for inclusion in the National Vulnerability Database. We are confident that this additional support will allow us to return to the processing rates we maintained prior to February 2024 within the next few months.

I hope the current time-outs and 503 errors are caused by the increasing usage instead of [Analygence](https://analygence.com/news/analygence-awarded-position-on-125m-nist-cybersecurity-and-privacy-support-services-capss-blanket-purchase-agreement-idiq/)'s consultants breaking up the API. 😅 We should get quite good services with the $125M of U.S. tax money invested in this! 💸

**Comment by P-T-I** [comment]
> @P-T-I Using the files might work for now, but we moved to the API mainly for the reason that the JSON feeds had been planned to retire in 2023, although it has other advantages, too.

I don't mean falling back to the json feeds from NIST; I was looking more along the lines of https://github.com/fkie-cad/nvd-json-data-feeds which has cached NIST data; and would be a nice fall back?

**Comment by oh2fih** [comment]
Ah, yes, those might live longer, and the repository states they are using the same API for collecting the data.

**Comment by oh2fih** [comment]
@P-T-I https://github.com/cve-search/cve-search/pull/1110 is on tap to add a command line option `-d` to `db_updater.py` for using this feature through CVE-Search; could be merged after there is a release of CveXplore that supports it. 😉
